-- Feel free to modify this file to match your development goal.
-- Here we only create 3 tables for demo purpose.

-- CREATE TABLE Users (
--     user_id SERIAL PRIMARY KEY,
--     email VARCHAR(255) UNIQUE NOT NULL,
--     first_name VARCHAR(50) NOT NULL,
--     last_name VARCHAR(50) NOT NULL,
--     address TEXT,
--     password VARCHAR(255) NOT NULL,
--     current_balance DECIMAL(10, 2) DEFAULT 0.00,
--     is_seller BOOLEAN DEFAULT FALSE
-- );
--
-- CREATE TABLE Products (
--     id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--     name VARCHAR(255) UNIQUE NOT NULL,
--     price DECIMAL(12,2) NOT NULL,
--     available BOOLEAN DEFAULT TRUE
-- );
--
-- CREATE TABLE Purchases (
--     id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--     uid INT NOT NULL REFERENCES Users(uesr_id), --我修改了这个uesr_id,原来的事id
--     pid INT NOT NULL REFERENCES Products(id),
--     time_purchased timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC')
-- );
--
-- -- The Reviews table 3/22 7:53 PM
-- -- only allows for reviews of products or sellers
-- CREATE TABLE Reviews (
--     review_id SERIAL PRIMARY KEY,
--     user_id INT NOT NULL REFERENCES Users(user_id),
--     comment TEXT NOT NULL,
--     review_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     product_id INT REFERENCES Products(id),
--     seller_id INT REFERENCES Users(user_id),
--     rating INT NOT NULL CHECK (rating BETWEEN 0 AND 5),
--     CONSTRAINT review_target_check CHECK (
--         (product_id IS NULL AND seller_id IS NOT NULL) OR
--         (product_id IS NOT NULL AND seller_id IS NULL)
--     )
-- );

-- Drop tables if they exist (in reverse order of dependencies)

-- Drop tables if they exist (in reverse order of dependencies)
DROP TABLE IF EXISTS Orders_Products;
DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS Reviews_Feedbacks;
DROP TABLE IF EXISTS Cart_Products;
DROP TABLE IF EXISTS Inventory;
DROP TABLE IF EXISTS Products;
DROP TABLE IF EXISTS Products_Categories;
DROP TABLE IF EXISTS Carts;
DROP TABLE IF EXISTS Accounts;

-- Create Accounts table
CREATE TABLE Accounts (
    user_id SERIAL PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    address TEXT,
    password VARCHAR(255) NOT NULL,
    current_balance DECIMAL(10,2) DEFAULT 0.00,
    is_seller BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create Products_Categories table
CREATE TABLE Products_Categories (
    category_id SERIAL PRIMARY KEY,
    category_name VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create Products table
CREATE TABLE Products (
    product_id SERIAL PRIMARY KEY,
    category_id INT NOT NULL,
    product_name VARCHAR(100) NOT NULL,
    description TEXT,
    image VARCHAR(255),
    owner_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (category_id) REFERENCES Products_Categories(category_id),
    FOREIGN KEY (owner_id) REFERENCES Accounts(user_id)
);

-- Create Inventory table
CREATE TABLE Inventory (
    inventory_id SERIAL PRIMARY KEY,
    seller_id INT NOT NULL,
    product_id INT NOT NULL,
    quantity INT NOT NULL DEFAULT 0,
    unit_price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(seller_id, product_id),
    FOREIGN KEY (seller_id) REFERENCES Accounts(user_id),
    FOREIGN KEY (product_id) REFERENCES Products(product_id)
);

-- Create Carts table
CREATE TABLE Carts (
    cart_id SERIAL PRIMARY KEY,
    user_id INT NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES Accounts(user_id)
);

-- Create Cart_Products junction table
CREATE TABLE Cart_Products (
    cart_id INT NOT NULL,
    product_id INT NOT NULL,
    seller_id INT NOT NULL,
    quantity INT NOT NULL DEFAULT 1,
    price_at_addition DECIMAL(10,2) NOT NULL,
    added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (cart_id, product_id, seller_id),
    FOREIGN KEY (cart_id) REFERENCES Carts(cart_id),
    FOREIGN KEY (product_id) REFERENCES Products(product_id),
    FOREIGN KEY (seller_id) REFERENCES Accounts(user_id)
);

-- Create Reviews_Feedbacks table
CREATE TABLE Reviews_Feedbacks (
    review_id SERIAL PRIMARY KEY,
    user_id INT NOT NULL,
    product_id INT,
    seller_id INT,
    comment TEXT NOT NULL,
    review_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    rating INT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES Accounts(user_id),
    FOREIGN KEY (product_id) REFERENCES Products(product_id),
    FOREIGN KEY (seller_id) REFERENCES Accounts(user_id),
    UNIQUE (user_id, product_id),  -- User can only review a product once
    UNIQUE (user_id, seller_id),   -- User can only review a seller once
    CHECK (
        (product_id IS NOT NULL AND seller_id IS NULL) OR
        (product_id IS NULL AND seller_id IS NOT NULL)
    ),
    CHECK (rating >= 1 AND rating <= 5)
);

-- Create Orders table
CREATE TABLE Orders (
    order_id SERIAL PRIMARY KEY,
    buyer_id INT NOT NULL,
    total_amount DECIMAL(10,2) NOT NULL,
    order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    num_products INT NOT NULL,
    order_status VARCHAR(20) NOT NULL DEFAULT 'Unfulfilled',
    CHECK (order_status IN ('Unfulfilled', 'Fulfilled')),
    FOREIGN KEY (buyer_id) REFERENCES Accounts(user_id)
);

-- Create Orders_Products junction table
CREATE TABLE Orders_Products (
    order_id INT NOT NULL,
    product_id INT NOT NULL,
    quantity INT NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    seller_id INT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'Unfulfilled',
    fulfillment_date TIMESTAMP,
    PRIMARY KEY (order_id, product_id, seller_id),
    CHECK (status IN ('Unfulfilled', 'Fulfilled')),
    FOREIGN KEY (order_id) REFERENCES Orders(order_id),
    FOREIGN KEY (product_id) REFERENCES Products(product_id),
    FOREIGN KEY (seller_id) REFERENCES Accounts(user_id)
);

-- Create indexes for foreign keys to improve query performance
CREATE INDEX idx_products_category ON Products(category_id);
CREATE INDEX idx_products_owner ON Products(owner_id);
CREATE INDEX idx_inventory_seller ON Inventory(seller_id);
CREATE INDEX idx_inventory_product ON Inventory(product_id);
CREATE INDEX idx_cart_user ON Carts(user_id);
CREATE INDEX idx_cart_products_cart ON Cart_Products(cart_id);
CREATE INDEX idx_cart_products_product ON Cart_Products(product_id);
CREATE INDEX idx_cart_products_seller ON Cart_Products(seller_id); -- Added index for seller_id in cart products
CREATE INDEX idx_reviews_user ON Reviews_Feedbacks(user_id);
CREATE INDEX idx_reviews_product ON Reviews_Feedbacks(product_id);
CREATE INDEX idx_reviews_seller ON Reviews_Feedbacks(seller_id);
CREATE INDEX idx_orders_buyer ON Orders(buyer_id);
CREATE INDEX idx_orders_products_order ON Orders_Products(order_id);
CREATE INDEX idx_orders_products_product ON Orders_Products(product_id);
CREATE INDEX idx_orders_products_seller ON Orders_Products(seller_id);

-- Add comments to tables
COMMENT ON TABLE Accounts IS 'Stores user account information for both buyers and sellers';
COMMENT ON TABLE Products_Categories IS 'Categories for products (e.g., Electronics, Clothing)';
COMMENT ON TABLE Products IS 'Product information catalog';
COMMENT ON TABLE Inventory IS 'Product inventory with quantity and pricing information per seller';
COMMENT ON TABLE Carts IS 'Shopping carts for users';
COMMENT ON TABLE Cart_Products IS 'Products in users shopping carts';
COMMENT ON TABLE Reviews_Feedbacks IS 'Reviews for either products or sellers';
COMMENT ON TABLE Orders IS 'Order information';
COMMENT ON TABLE Orders_Products IS 'Products within an order with specific seller and status';

-- Create views to simplify complex queries
CREATE OR REPLACE VIEW product_details AS
SELECT
    p.product_id,
    p.product_name,
    p.description,
    p.image,
    p.category_id,
    pc.category_name,
    p.owner_id,
    a.full_name AS owner_name,
    p.created_at,
    p.updated_at,
    COALESCE(AVG(r.rating), 0) AS average_rating,
    COUNT(r.review_id) AS review_count
FROM Products p
JOIN Products_Categories pc ON p.category_id = pc.category_id
JOIN Accounts a ON p.owner_id = a.user_id
LEFT JOIN Reviews_Feedbacks r ON p.product_id = r.product_id
GROUP BY p.product_id, pc.category_name, a.full_name;

CREATE OR REPLACE VIEW inventory_details AS
SELECT
    i.inventory_id,
    i.seller_id,
    a.full_name AS seller_name,
    i.product_id,
    p.product_name,
    p.category_id,
    pc.category_name,
    p.image,
    i.quantity,
    i.unit_price,
    i.created_at,
    i.updated_at,
    COALESCE(AVG(r.rating), 0) AS seller_rating
FROM Inventory i
JOIN Accounts a ON i.seller_id = a.user_id
JOIN Products p ON i.product_id = p.product_id
JOIN Products_Categories pc ON p.category_id = pc.category_id
LEFT JOIN Reviews_Feedbacks r ON i.seller_id = r.seller_id
GROUP BY i.inventory_id, a.full_name, p.product_name, p.category_id, pc.category_name, p.image;
