-- Feel free to modify this file to match your development goal.
-- Here we only create 3 tables for demo purpose.

CREATE TABLE Users (
    user_id SERIAL PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    address TEXT,
    password VARCHAR(255) NOT NULL,
    current_balance DECIMAL(10, 2) DEFAULT 0.00,
    is_seller BOOLEAN DEFAULT FALSE
);

CREATE TABLE Products (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) UNIQUE NOT NULL,
    price DECIMAL(12,2) NOT NULL,
    available BOOLEAN DEFAULT TRUE
);

CREATE TABLE Purchases (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    uid INT NOT NULL REFERENCES Users(uesr_id), --我修改了这个uesr_id,原来的事id
    pid INT NOT NULL REFERENCES Products(id),
    time_purchased timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC')
);

-- The Reviews table 3/22 7:53 PM
-- only allows for reviews of products or sellers
CREATE TABLE Reviews (
    review_id SERIAL PRIMARY KEY,
    user_id INT NOT NULL REFERENCES Users(user_id),
    comment TEXT NOT NULL,
    review_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    product_id INT REFERENCES Products(id),
    seller_id INT REFERENCES Users(user_id),
    rating INT NOT NULL CHECK (rating BETWEEN 0 AND 5),
    CONSTRAINT review_target_check CHECK (
        (product_id IS NULL AND seller_id IS NOT NULL) OR
        (product_id IS NOT NULL AND seller_id IS NULL)
    )
);
